# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='department',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='department',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Department'),
            preserve_default=False,
        ),
    ]
