# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20190711_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistration',
            name='email',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department'),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='inter_doc',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='ssc_doc',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
