# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20190711_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('TE', 'TELUGU'), ('EN', 'ENGLISH'), ('MA', 'MATHS'), ('PH', 'PHYSICS'), ('CS', 'COMPUTERS')], max_length=20),
        ),
    ]
