# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20190711_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='profile_pic',
            field=models.ImageField(upload_to='staff/images/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='inter_doc',
            field=models.FileField(upload_to='documents/inter/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='ssc_doc',
            field=models.FileField(upload_to='documents/ssc/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='profile_pic',
            field=models.ImageField(upload_to='student/images/'),
        ),
    ]
