# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20190716_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
